apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app: guestbook-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: guestbook-app
    name: guestbook-pod
