apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
  labels:
    app: guestbook-app
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guestbook-pod
      app: guestbook-app
  template:
    metadata:
      name: guestbook-pod
      labels:
        name: guestbook-pod
        app: guestbook-app
    spec:
      containers:
      - name: guestbook
        image: kubernetes/guestbook:v2 
        ports:
        - containerPort: 3000
