apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-service
    app: guestbook-app
spec:
  ports:
  - port: 6379
  selector:
    app: guestbook-app
    name: redis-pod
